sudo: required
language: node_js
node_js:
- '9'
addons:
    chrome: stable
branches:
  only:
  - master
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
after_success:
- npm run build
env:
  global:
  - GIT_NAME="Pedro Gutiérrez"
  - GIT_EMAIL="pedrogp9_6_93@hotmail.com"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"
