sudo: required
language: node_js
node_js:
- '9'
addons:
  chrome: stable
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- openssl aes-256-cbc -K $encrypted_ed587a115bcb_key -iv $encrypted_ed587a115bcb_iv
  -in .travisGitHub.enc -out .travisGitHub -d
after_success:
- npm run lint
- npm run build
- npx lcov-result-merger "coverage-*/lcov.info" lcov.info
- cat ./lcov.info | node_modules/coveralls/bin/coveralls.js
- npm run gh-pages-travis
env:
  global:
  - SSH_KEY=".travisGitHub"
  - GIT_NAME="Pedro Gutiérrez"
  - GIT_EMAIL="pedrogp9_6_93@hotmail.com"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"
